import { PropsWithChildren } from 'react';

import type { Metadata, NextPage } from 'next';
import { Inter } from 'next/font/google';

import '@/styles/globals.css';
import { cn } from '@/lib/tailwind/utils';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: NextPage<PropsWithChildren> = ({ children }) => (
  <html lang="pt-br">
    <body
      className={cn(
        inter.variable,
        'antialiased font-sans flex flex-col min-h-screen'
      )}
    >
      {children}
    </body>
  </html>
);

export default RootLayout;
